>P1;template
structureX:template :1 :A :139 :A : : : :
---DHPKMDKLKEIIREQLQRKQNSKIIVFTNYRETAKKIVN------E-LVKDGIKAKRFVGQAS-------KQREQK
--------LILDEFARGEFNVLVATSVG----EEG-----LDVPEVDLVVFYEPVPSAIRSIQRRGRTGRHMPGRVIIL
MAKGTRDEAYYWSSR*

>P1;ERCC_mut
sequence:ERCC_mut : : : : : : : : 
VLESNPKWEALTEVLKEIEAENKESEAFLLRLYRKTFEKDSKAEEVWMKKKKKRKLTLTQMVGKPEELEEEGDVEEGYR
REISSSPESCPEEIKHEEFDVNLSSDAAFGILKEPLTIIHLHEVEPRYVVLYDAELTFVFQLEIYRASRPGKPLRVYFL
IYGGSTEEQRYLTAL*
